#!/usr/bin/env python3
"""CMT-2 read-only diagnostic: inspect experimental actions without API calls.

Works against `runs/*.jsonl` generated by llmcognition v0.1. Never loads
OPENAI_API_KEY or sealed task data. Does not modify experiments or metrics.
"""
from __future__ import annotations

import argparse
import collections
import json
from pathlib import Path

CONDITIONS = ("A", "B", "C", "D")
POLICIES = ("adaptive", "direct", "random", "count", "always", "symbolic")


def _percent(n: int, total: int) -> str:
    return f"{n / total * 100:.1f}%" if total else "NA"


def _fmt(value: float | None) -> str:
    return "NA" if value is None else f"{value:.3f}"


def _mean(values: list[float]) -> float | None:
    return sum(values) / len(values) if values else None


def diagnose(rows: list[dict], *, source: str = "results") -> str:
    if not rows:
        raise ValueError("Results file contains no rows")
    keys = [(r["case_id"], r["policy"]) for r in rows]
    if len(keys) != len(set(keys)):
        raise ValueError("Duplicate (case_id, policy) entries")
    by_policy: dict[str, list[dict]] = collections.defaultdict(list)
    cases: dict[str, list[dict]] = collections.defaultdict(list)
    for row in rows:
        by_policy[row["policy"]].append(row)
        cases[row["case_id"]].append(row)

    adaptive = by_policy.get("adaptive", [])
    if not adaptive:
        raise ValueError("Cannot diagnose metacognition: no adaptive policy rows")
    arms: dict[str, list[dict]] = {c: [] for c in CONDITIONS}
    for row in adaptive:
        condition = row["condition"]
        if condition not in arms:
            raise ValueError(f"Unexpected condition: {condition}")
        arms[condition].append(row)

    out: list[str] = [
        "# CMT-2 pilot diagnostic (local and read-only)", "",
        f"Input file: `{source}`", "",
        f"**Independent cases:** {len(cases)}; **policy rows:** {len(rows)}. "
        "Policy rows are paired repeats, NOT independent tasks.", "",
        "## Condition-wise adaptive behavior", "",
        "| Condition | N | Queried | Query rate | Critical queries | Critical / all queries | "
        "Accuracy | Initial accuracy | Utility |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for c in CONDITIONS:
        arm = arms[c]
        checks = [r for r in arm if r["queried"]]
        hits = sum(bool(r["critical_hit"]) for r in arm)
        out.append(
            f"| {c} | {len(arm)} | {len(checks)} | {_percent(len(checks),len(arm))} | "
            f"{hits} | {_percent(hits,len(checks))} | "
            f"{_fmt(_mean([float(r['correct']) for r in arm]))} | "
            f"{_fmt(_mean([float(r['initial_correct']) for r in arm if r.get('initial_correct') is not None]))} | "
            f"{_fmt(_mean([float(r['utility']) for r in arm]))} |"
        )
    out += ["", "## Policy comparison (each row is a paired policy result)", "",
            "| Policy | N | Accuracy | Utility | Query rate | Critical precision |",
            "|---|---:|---:|---:|---:|---:|"]
    for policy in POLICIES:
        rr = by_policy.get(policy, [])
        if not rr:
            continue
        checks = [r for r in rr if r["queried"]]
        out.append(
            f"| {policy} | {len(rr)} | {_fmt(_mean([float(r['correct']) for r in rr]))} | "
            f"{_fmt(_mean([float(r['utility']) for r in rr]))} | "
            f"{_percent(len(checks),len(rr))} | "
            f"{_percent(sum(bool(r['critical_hit']) for r in checks),len(checks))} |"
        )

    if all(arms.values()):
        q = {c: _mean([float(r["queried"]) for r in arms[c]]) for c in CONDITIONS}
        discrimin = (q["B"] + q["C"] - q["A"] - q["D"]) / 2
        out += ["", "## Reading the discrimination result", "",
                f"**D = (Q_B + Q_C − Q_A − Q_D) / 2 = {discrimin:+.3f}.**", ""]
        total_q = sum(bool(r["queried"]) for r in adaptive)
        if total_q == 0:
            out.append("The model **never requested additional information** in this sample.")
        elif total_q == len(adaptive):
            out.append("The model **requested additional information in every case**; it did not selectively seek information.")
        elif abs(discrimin) < 1e-12:
            out.append("The adaptive policy queried equally often in B/C versus A/D, "
                       "but this may conceal different per-condition rates. Examine the table above.")
        elif discrimin > 0:
            out.append("Adaptive lookups were more frequent when data were missing/contradictory "
                       "than when complete. This is consistent with selectivity, not conclusive evidence.")
        else:
            out.append("Adaptive lookups were more frequent when data were sufficient; "
                       "this runs against the experiment's selectivity hypothesis.")
    else:
        missing = [c for c in CONDITIONS if not arms[c]]
        out += ["", "**Discrimination is not estimable:** missing conditions " + ", ".join(missing) + "."]

    bc = arms["B"] + arms["C"]
    queries_bc = [r for r in bc if r["queried"]]
    hit = sum(bool(r["critical_hit"]) for r in queries_bc)
    out += ["", "## Diagnostic-query relevance", "",
            f"Among B/C there were **{len(queries_bc)} queries**; **{hit}** selected the "
            f"single diagnostic query ({_percent(hit,len(queries_bc))}).",
            "Randomly choosing among six menu options hits the diagnostic choice "
            "with probability 1/6 (16.7%) in each B/C case.", ""]

    if len(cases) < 100:
        out.append(f"**Small-sample warning:** only {len(cases)}/100 cases were tested; "
                   "this is a pilot, not the registered main experiment.")
    sizes = {c: len(arms[c]) for c in CONDITIONS}
    if len(set(sizes.values())) != 1:
        out.append(f"**Imbalanced pilot:** per-condition sample sizes: {sizes}. "
                   "The first N cases of a shuffled dataset need not be evenly balanced.")
    by_case_counts = {k: len(v) for k,v in cases.items()}
    if len(set(by_case_counts.values())) > 1:
        out.append("**Incomplete policy pairing warning:** some cases have fewer policy rows.")

    out += ["", "## Individual adaptive decisions (local review only)", "",
            "| Case ID | Condition | Initial action | Query selected | Critical? | "
            "Initial correct? | Final correct? | Confidence |",
            "|---|:---:|---|:---:|:---:|:---:|:---:|---:|"]
    for r in adaptive:
        out.append(
            f"| {r['case_id']} | {r['condition']} | {r.get('initial_action') or 'NA'} | "
            f"{'yes' if r['queried'] else 'no'} | "
            f"{'yes' if r['critical_hit'] else 'no'} | "
            f"{r.get('initial_correct','NA')} | {r['correct']} | "
            f"{_fmt(r.get('initial_confidence'))} |"
        )
    out += ["", "---", "",
            "**Interpretation limit:** a model's query-selection behavior is evidence of functional "
            "monitoring/control at most; it does not demonstrate subjective consciousness. "
            "In the current prompt, query options and costs are explicitly provided.", "",
            "**Privacy:** Do not commit this report, the run JSONL, or the private dataset "
            "to a public GitHub repository; they expose answer correctness and held-out labels.", ""]
    return "\n".join(out)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results", default="runs/pilot.jsonl", type=Path)
    parser.add_argument("--output", type=Path, help="Optional report path inside ignored reports/")
    args = parser.parse_args()
    with args.results.open(encoding="utf-8") as f:
        rows = [json.loads(line) for line in f if line.strip()]
    report = diagnose(rows, source=str(args.results))
    if args.output:
        if not args.output.resolve().is_relative_to(Path("reports").resolve()):
            parser.error("Use an output path under reports/ (gitignored for private results)")
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(report, encoding="utf-8")
        print(f"Wrote private diagnostic: {args.output}")
    else:
        print(report)


if __name__ == "__main__":
    main()
